eureka:
  instance:
    appname: get-statement
    hostname: localhost

server:
  port: 7011

spring:
  kafka:
    bootstrap-servers: 142.93.60.121:9092

topic:
  statement:
    jobs: jobs2
    sender: sender2
    update: update3

