server:
  port: 7011

spring:
  kafka:
    bootstrap-servers: 142.93.60.121:9092

  jackson:
    serialization:
      write-dates-as-timestamps: false

topic:
  statement:
    jobs: jobs2
    sender: sender4
    update: update3

